name: "Install and cache Node Modules"
description: "Some description"
inputs:
  caching:
    required: false
    description: "enable or disable caching"
    default: "true"
runs:
  using: "composite"
  steps:
    #add logic if cache is trie it should work

    - name: Cache node modules
      if: ${{ inputs.caching =='true'}}
      id: cache-step
      uses:
        actions/cache@v5
        # specify the path to cache it's for linux runner
      with:
        path: ~/.npm
        key:
          ${{runner.os}}-cache-file-${{ hashFiles('**/package-lock.json') }}
          # specify restore keys to restore cache if there is no exact match
        restore-keys: |
          ${{runner.os}}-cache-file-
          ${{runner.os}}-
    - name: Display cache content
      shell: bash
      # display cache content
      run: echo '${{ toJson(steps.cache-step.outputs)}}'
    - name: Install dependencies
      shell: bash
      run: npm install
