name: Doker Test
on: push
jobs:
    test-docker-container:
        runs-on: ubuntu-latest
        container:
            image: node:26-alpine3.23
            env:
                NODE_ENV: development
            ports:
                - 80
        steps:
            - name: Display node version
              run: |
                  node -v
                  cat /etc/os-release
            - name: Print new Node version
              uses: docker://node:18-buster-slim
              with:
                  args: -v
