name: Fourth Workflow After Copy Repository Workflow
on:
    workflow_run:
        workflows: ["Copy Repository Workflow"]
        # works after the workflow "Copy Repository Workflow" is completed
        types:
            - completed
jobs:
    success-command:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - run: echo "Repository copied successfully!"
    failure-command:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        steps:
            - run: echo "Failed to copy repository."
