name: Functions Workflow
on: push
jobs:
    functions-command:
        runs-on: ubuntu-latest
        steps:
            - name: Failed step
              id: failed_step
              run: exit 1
            - name: first step
              run: echo "First step"
            - name: Runs on Cancelled
              if: ${{ cancelled() }}
              run: echo "This job was cancelled"
            - name: Runs on any case
              if: ${{ always() }}
              run: echo "This job runs regardless of the previous job's result"
            - name: Runs on success
              if: ${{ success() }}
              run: echo "This job runs only if the previous job succeeded"
            - name: Runs on failure
              if: ${{ failure() }}
              run: echo "This job runs only one of the previous job is failed"
            - name: Check error
              if: ${{ steps.failed_step.conclusion == 'failure' }}
              run: echo "This job runs only if the failed step is failed"
    second-job:
        runs-on: ubuntu-latest
        needs: functions-command
        if: ${{failure()}}
        steps:
            - name: second step
              run: echo "This job runs only if the first job failed"
