name: Secret Workflow
on: push
jobs:
    secrets-command:
        runs-on: ubuntu-latest
        steps:
            - name: show secrets
              run: |
                  echo 'status: ${{vars.STATUS}}'
                  echo  'secret: ${{secrets.PASSWORD}}'
                  echo  $JOB_CUSTOM_VAR
                  echo  $STEP_CUSTOM_VAR
                  echo  $NEW_CUSTOM_VAR
