name: Secret Workflow
on: push
jobs:
    secrets-command:
        runs-on: ubuntu-latest
        environment:
            name: "staging"
        steps:
            - name: show secrets
              run: |
                  echo 'status: ${{vars.STATUS}}'
                  echo  'secret: ${{secrets.PASSWORD}}'
