name: Main Branches Workflow
on:
    push:
        branches:
            - main
        # tags:
        #     - "v1.*.*"
        paths:
            #only trigger workflow if files with .html extension are changed
            - "**.html"
jobs:
    run-test-command:
        runs-on: ubuntu-latest
        steps:
            - name: test command
              run: echo "Testing!"
