name: Copy Repository Workflow
on: push
jobs:
    copy-repository:
        runs-on: ubuntu-latest
        steps:
            - name: list files in current directory before copying repositorys
              run: ls -a
            - name: copy repository
              run: |
                  git init
                  git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}/$GITHUB_REPOSITORY.git"
                  git fetch origin
                  git checkout main
            #- uses: actions/checkout@v6
            - name: list files in current directory after copying repositorys
              run: ls -a
