name: Third Workflow
on: push
jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
            - name: Show current directory and list files
              run: |-
                  pwd
                  ls -a
