name: Test Timeout
on: push
jobs:
    test-timeout:
        runs-on: ubuntu-latest
        # job timout if finish and job still working exit from workflow
        timeout-minutes: 1
        steps:
            - name: Some Step
              run: sleep 200
